name: Step - Deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        description: 'Environment to deploy to'
      resource_group_name:
        required: true
        type: string
        description: 'Resource group name'
      app_service_name:
        required: true
        type: string
        description: 'App service name'
      app_service_slot_name:
        required: false
        type: string
        description: 'App service slot name'
        default: 'slot'
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy:
    name: Deploy ${{ inputs.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Bicep
        run: |
          az deployment group create \
            --name ${{ inputs.env }}-deployment-${{ github.run_number }} \
            --template-file infrastructure/main.bicep \
            --resource-group ${{ inputs.resource_group_name }} \
            --verbose

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ inputs.app_service_name }}
          slot-name: slot
          package: artifacts/

      - name: Swap slots
        run: |
          az webapp deployment slot swap -g ${{ inputs.resource_group_name }} -n ${{ inputs.app_service_name }} --slot ${{ inputs.app_service_slot_name }} --target-slot production --verbose
